<!DOCTYPE html>
<html lang="en">

<head>
<#include "/templates/google-tag.ftlh">
    <meta charset="UTF-8">
    <title>Command Group</title>
    <link rel="stylesheet" href="style.css">
    <style>
    li {
        font-size: 13px;
    }
    </style>
</head>

<body>
    <ul>
        <li><a href="commands/all-commands.html" target="group-cmds-frame">All Commands</a></li>
        <li><a href="commands/3D%20Commands/index.html" target="group-cmds-frame">3D Commands</a></li>
        <li><a href="commands/Algebra%20Commands/index.html" target="group-cmds-frame">Algebra Commands</a></li>
        <li><a href="commands/CAS%20Specific%20Commands/index.html" target="group-cmds-frame">CAS Specific Commands</a></li>
        <li><a href="commands/Chart%20Commands/index.html" target="group-cmds-frame">Chart Commands</a></li>
        <li><a href="commands/Conic%20Commands/index.html" target="group-cmds-frame">Conic Commands</a></li>
        <li><a href="commands/Discrete%20Math%20Commands/index.html" target="group-cmds-frame">Discrete Math Commands</a></li>
        <li><a href="commands/Financial%20Commands/index.html" target="group-cmds-frame">Financial Commands</a></li>
        <li><a href="commands/Function%20Commands/index.html" target="group-cmds-frame">Function Commands</a></li>
        <li><a href="commands/GeoGebra%20Commands/index.html" target="group-cmds-frame">GeoGebra Commands</a></li>
        <li><a href="commands/Geometry%20Commands/index.html" target="group-cmds-frame">Geometry Commands</a></li>
        <li><a href="commands/List%20Commands/index.html" target="group-cmds-frame">List Commands</a></li>
        <li><a href="commands/Logic%20Commands/index.html" target="group-cmds-frame">Logic Commands</a></li>
        <li><a href="commands/Optimization%20Commands/index.html" target="group-cmds-frame">Optimization Commands</a></li>
        <li><a href="commands/Probability%20Commands/index.html" target="group-cmds-frame">Probability Commands</a></li>
        <li><a href="commands/Scripting%20Commands/index.html" target="group-cmds-frame">Scripting Commands</a></li>
        <li><a href="commands/Spreadsheet%20Commands/index.html" target="group-cmds-frame">Spreadsheet Commands</a></li>
        <li><a href="commands/Statistics%20Commands/index.html" target="group-cmds-frame">Statistics Commands</a></li>
        <li><a href="commands/Text%20Commands/index.html" target="group-cmds-frame">Text Commands</a></li>
        <li><a href="commands/Transformation%20Commands/index.html" target="group-cmds-frame">Transformation Commands</a></li>
        <li><a href="commands/Vector%20and%20Matrix%20Commands/index.html" target="group-cmds-frame">Vector and Matrix Commands</a></li>
    </ul>
</body>

</html>