<!DOCTYPE html>
<html lang="en">

<head>
<#include "/templates/google-tag.ftlh">
    <meta charset="UTF-8">
    <title>GeoGebra Help</title>
    <link rel="stylesheet" href="style.css">
</head>

<body>
    <iframe id="cmd-group-frame" name="cmd-group-frame" src="cmd-group.html"></iframe>
    <iframe id="group-cmds-frame" name="group-cmds-frame" src="commands/all-commands.html"></iframe>
    <iframe id="cmd-detail-frame" name="cmd-detail-frame"></iframe>
</body>

</html>